apiVersion: v1
kind: Namespace
metadata:
  name: chaoxing-1
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: collector
  namespace: chaoxing-1
spec:
  schedule: "*/20 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          containers:
            - name: collector
              image: "awesomepayne/collector:${TAG}"
              env:
                - name: LOG_LEVEL
                  value: INFO
