# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: CI

on:
  push:
    paths-ignore:
      - .gitignore
      - README.md
      - '.github/ISSUE_TEMPLATE/**'
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ${{matrix.os}}
    strategy:
      fail-fast: false
      max-parallel: 15
      matrix:
        python-version: [ "3.6",  "3.7", "3.8", "3.9", "3.10" ]
        os: [
            ubuntu-18.04, ubuntu-20.04, ubuntu-latest,
            macos-10.15, macos-11, macos-latest,
        ]

    steps:
      - uses: actions/checkout@v2
      - name: Set up
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Verify feasibility
        run: |
          python -u main.py
